GET http://localhost:3001/notes/

###
DELETE https://radiant-ridge-20224.herokuapp.com/notes/4

###
GET http://localhost:3001/notes/1

###
POST https://radiant-ridge-20224.herokuapp.com/notes
Content-Type: application/json

{
    "content": "hyvälle"
}